### ISSUE TITLE
Magento OpenSource 2.4.7-p1 Csp Issue on Checkout

### ISSUE THREAD

**Issue by JDavidVR** [swissup/module-ignition#4]
Latest Magento 2.4.7-p1, has broken this module functionality ajax error, due to csp inline rule

With this module I was able to disable it: https://github.com/yireo/Yireo_DisableCsp but my question is if there is a better way to bypass the csp validation?

**Comment by vovayatsyuk** [comment]
~~Can you please add steps to reproduce the issue? For me, popup is not shown because all requests at checkout using `global: false` property and `ajaxError` event is not fired.~~

**Comment by vovayatsyuk** [comment]
My bad. Checked once again and now I see that it shows empty popup. Will see if I can fix it.

**Comment by vovayatsyuk** [comment]
Fixed: https://github.com/swissup/module-ignition/commit/dfb8fb9fee50d3d6a0af9c56df32c4af2a85b90b, https://github.com/swissup/module-ignition/commit/930b4e896284fa5d5665162188b85e710635db31

**Comment by JDavidVR** [comment]
Thanks I can confirm it is workin on dev-master version:

<img width="1481" alt="image" src="https://github.com/user-attachments/assets/88f0a0a2-abd1-4231-8c5e-f60b1c5469b4">
